name: pytest

on:
  push:
    branches: [ hd_de24 ]
  
  workflow_dispatch:
    inputs:
      log_errors:
        description: "Skapa loggfil vid testfel?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

env:
  APP_NAME: wether-app 
  GREETINGS: "Kör tester"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "PWD"
          pwd
          echo "Lista filer:"
          ls -R
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Installera paket
        run: pip install -r requirements.txt
      
      - name: Debug
        run: pip list
      
      - name: Kör pytest
        run: |
          set -o pipefail
          echo "$GREETINGS"
          pytest test_weather_integration.py test_weather_unit.py test_fail.py \
            --doctest-modules \
            --junitxml=junit/test-results.xml \
            --cov=. \
            --cov-report=xml \
            --cov-report=html \
            > pytest_output.log 2>&1

      - name: Ladda upp pytest log
        if: always() && failure() && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.log_errors == 'true'))
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: pytest_output.log

  build:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - uses: actions/checkout@v4
      - name: Bygger docker images
        run: |
          echo "Alla tester är klara! Bygger $APP_NAME"
