
name: pytest

on:
  push:
    branches: [ hd_de24 ]
  
  workflow_dispatch:
    inputs:
      log_errors:
        description: "Skapa loggfil vid testfel?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

env:
 APP_NAME: wether-app 
 GREETINGS: "Running unitest"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "$GREETINGS"
          pytest -v ./test_wether_integration.py ./test_wether_unitest.py

  build:
    runs-on: ubuntu-latest
    needs: test 
    if: success() 
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          echo "Alla tester Ã¤r klara! Bygger $APP_NAME"
          
  log_error:
     runs-on: ubuntu-latest
     needs: test 
     if: failure() && github.event.inputs.log_errors == 'true'
     steps:
       - uses: actions/checkout@v4
       - name: Skapar loggfil 
         run: echo "Tester misslyckades, logg sparad." > error_log.txt


       - name: Ladda upp logg som artefakt
         uses: actions/upload-artifact@v4
         with:
          name: pytest-error-log
          path: error_log.txt
    
    
 
