name: pytest

on:
  push:
    branches: [ hd_de24 ]
  
  workflow_dispatch:
    inputs:
      log_errors:
        description: "Skapa loggfil vid testfel?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

env:
  APP_NAME: wether-app 
  GREETINGS: "Kör tester"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Kör pytest
        run: |
          pip install pytest pytest-cov
          pytest test_wether_integration.py test_wether_unitest.py \
            --doctest-modules \
            --junitxml=junit/test-results.xml \
            --cov=com \
            --cov-report=xml \
            --cov-report=html > pytest_output.log 2>&1

      - name: Ladda upp pytest log
        if: always() && failure() && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.log_errors == 'true'))
        uses: actions/upload-artifact@v4
        with:
          name: pytest log
          path: pytest_output.log